package br.com.vinicius.personalfinance.fixtures

import org.apache.pdfbox.pdmodel.PDDocument
import org.apache.pdfbox.pdmodel.PDDocumentInformation
import org.apache.pdfbox.pdmodel.PDPage
import org.apache.pdfbox.pdmodel.PDPageContentStream
import org.apache.pdfbox.pdmodel.encryption.AccessPermission
import org.apache.pdfbox.pdmodel.encryption.StandardProtectionPolicy
import org.apache.pdfbox.pdmodel.font.PDType1Font
import org.apache.pdfbox.pdmodel.font.Standard14Fonts
import java.io.ByteArrayOutputStream
import java.util.Calendar
import java.util.GregorianCalendar
import java.util.Locale
import java.util.TimeZone

/**
 * Builds fixture PDFs from a [InterPositionFixture.Case].
 *
 * Generated rather than committed, on purpose:
 *
 * - a binary blob cannot be reviewed, and ADR 0029 warns that residual metadata
 *   is exactly how personal data escapes;
 * - the source of every fixture stays readable in Kotlin, so a reviewer can see
 *   that the content is invented;
 * - explicit fixture pages preserve the observed page-provenance shape without
 *   ever carrying a real report into the repository.
 *
 * Document timestamps are pinned, so nothing about the build clock leaks into a
 * fixture. The bytes of a *protected* fixture still differ between runs because
 * encryption derives a random salt, by design. Extracted text is reproducible.
 */
object FixturePdfBuilder {
    private const val FONT_SIZE = 8f

    private const val LEADING = 11f

    private const val MARGIN_LEFT = 32f

    private const val MARGIN_TOP = 790f

    fun build(case: InterPositionFixture.Case): ByteArray {
        PDDocument().use { document ->
            case.pages.forEach { pageLines -> writePage(document, pageLines) }
            document.documentInformation = pinnedInformation()
            if (case.protected) {
                document.protect(
                    StandardProtectionPolicy(
                        InterPositionFixture.TEST_PASSWORD,
                        InterPositionFixture.TEST_PASSWORD,
                        AccessPermission(),
                    ),
                )
            }
            val out = ByteArrayOutputStream()
            document.save(out)
            return out.toByteArray()
        }
    }

    private fun writePage(
        document: PDDocument,
        lines: List<String>,
    ) {
        val page = PDPage()
        document.addPage(page)
        PDPageContentStream(document, page).use { stream ->
            stream.beginText()
            stream.setFont(PDType1Font(Standard14Fonts.FontName.COURIER), FONT_SIZE)
            stream.setLeading(LEADING)
            stream.newLineAtOffset(MARGIN_LEFT, MARGIN_TOP)
            lines.forEach { line ->
                stream.showText(sanitizeForWinAnsi(line))
                stream.newLine()
            }
            stream.endText()
        }
    }

    /**
     * The observed Portuguese labels fit WinAnsi, including the accents used by
     * the Inter export. Characters outside the single-byte fixture alphabet are
     * replaced so an accidental unsupported glyph cannot make generation flaky.
     */
    private fun sanitizeForWinAnsi(line: String): String =
        line.map { character -> if (character.code in 32..255) character else '?' }.joinToString("")

    /** Fixed timestamps, so the generated bytes do not depend on when they were built. */
    private fun pinnedInformation(): PDDocumentInformation =
        PDDocumentInformation().apply {
            producer = "personal-finance-platform fixtures"
            creator = "synthetic fixture generator"
            val pinned =
                GregorianCalendar(TimeZone.getTimeZone("UTC"), Locale.ROOT).apply {
                    clear()
                    set(2026, Calendar.FEBRUARY, 2, 8, 15, 0)
                }
            creationDate = pinned
            modificationDate = pinned
        }
}
