spring:
  application:
    name: personal-finance-platform
  main:
    banner-mode: "off"

server:
  address: 127.0.0.1

management:
  endpoints:
    web:
      exposure:
        include: health,info
  endpoint:
    health:
      show-details: never
